from strategy import object_filter
from strategy import filter_strategy

object_filter.select_object_from_my(filter_strategy.is_in_week_trend_buy)
object_filter.select_object_from_etf(filter_strategy.is_in_week_trend_buy)
object_filter.select_object_from_plate(filter_strategy.is_in_week_trend_buy)
object_filter.select_plate(filter_strategy.is_in_week_trend_buy)
print('end')
